print("Create")
l=[]
print(l)

l= [1, "string",12.3, 'Hello',25]
print(l)
print("insert variable into list")
sentence= 'What  a wonderful life'
my_list = list(sentence)
print(my_list)
print("break up")
my_list1=sentence.split(' ')
print(my_list1)
print("Displaying elements")

print(my_list1[-1])
print(my_list1[0])
print("Adding an element")
n=[]
n.append(15)
print(n)
print("Adding an element to the desired position")
n.insert(2,75)
print(n)
n.insert(1,30)
print(n)
n.insert(1,45)
print("Index of element")
n.index(30)
print(n.index(30))
# n.clear(15)
print(n)
n.remove(30)
print(n)
print("reverse")
n.reverse()
print(n)
print("Count elements")
m=n.count(75)
print(m)
n.insert(3,75)
m=n.count(75)
print(m)
print(sum(n))
print(n)
print(min(n))
print(max(n))
l1=[100,456]
n.append(l1)
print(n)

add='extra';
n.append(add)
print(n)
n.extend(add)
print(n)